-- ----------------------------
-- Table structure for `enumeration_blocks`
-- ----------------------------
DROP TABLE IF EXISTS `enumeration_blocks`;
CREATE TABLE `enumeration_blocks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reference_number` int(11) DEFAULT NULL,
  `sub_enumeration_number` int(11) DEFAULT NULL,
  `number_of_houses` int(11) DEFAULT NULL,
  `number_of_citizens` int(11) DEFAULT NULL,
  `state_id` int(11) DEFAULT NULL,
  `division_id` int(11) DEFAULT NULL,
  `district_id` int(11) DEFAULT NULL,
  `revenue_block_id` int(11) DEFAULT NULL,
  `panchayat_id` int(11) DEFAULT NULL,
  `status` tinyint(1) DEFAULT '1',
  `catalog_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `enumeration_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `enu_nic_upload_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `supervising_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `super_nic_upload_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `draft_list_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `draft_list_edit_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `final_list_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'NYS',
  `report_status` tinyint(1) DEFAULT '0',
  `remarks` text COLLATE utf8_unicode_ci,
  `created_by` int(11) DEFAULT NULL,
  `modified_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=315 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of enumeration_blocks
-- ----------------------------
INSERT INTO `enumeration_blocks` VALUES ('1', '1', '1', '68', '415', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', 'Hi', null, null, null, '2012-02-27 15:19:36');
INSERT INTO `enumeration_blocks` VALUES ('2', '1', '2', '82', '471', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', '', null, null, null, '2012-02-22 12:13:05');
INSERT INTO `enumeration_blocks` VALUES ('3', '2', null, '116', '657', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 15:36:43');
INSERT INTO `enumeration_blocks` VALUES ('4', '3', null, '96', '691', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 12:16:34');
INSERT INTO `enumeration_blocks` VALUES ('5', '4', null, '47', '286', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 12:19:36');
INSERT INTO `enumeration_blocks` VALUES ('6', '5', null, '92', '558', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 13:54:40');
INSERT INTO `enumeration_blocks` VALUES ('7', '6', null, '95', '578', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', '', null, null, null, '2012-02-24 16:35:51');
INSERT INTO `enumeration_blocks` VALUES ('8', '7', null, null, null, '1', null, '1', '1', '1', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-18 14:06:30');
INSERT INTO `enumeration_blocks` VALUES ('9', '8', null, '100', '648', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:29');
INSERT INTO `enumeration_blocks` VALUES ('10', '9', '1', '95', '564', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:28');
INSERT INTO `enumeration_blocks` VALUES ('11', '9', '2', '27', '196', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:28');
INSERT INTO `enumeration_blocks` VALUES ('12', '10', null, '71', '455', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:27');
INSERT INTO `enumeration_blocks` VALUES ('13', '11', null, '56', '428', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:27');
INSERT INTO `enumeration_blocks` VALUES ('14', '12', null, '63', '444', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:26');
INSERT INTO `enumeration_blocks` VALUES ('15', '13', null, '77', '444', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:25');
INSERT INTO `enumeration_blocks` VALUES ('16', '14', null, '72', '477', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 14:06:24');
INSERT INTO `enumeration_blocks` VALUES ('17', '15', null, null, null, '1', null, '1', '1', '1', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', null, null, null, null, '2012-02-24 15:36:45');
INSERT INTO `enumeration_blocks` VALUES ('18', '16', null, '61', '460', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 15:36:49');
INSERT INTO `enumeration_blocks` VALUES ('19', '17', null, '71', '480', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 15:36:47');
INSERT INTO `enumeration_blocks` VALUES ('20', '18', null, '154', '694', '1', null, '1', '1', '1', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 12:25:09');
INSERT INTO `enumeration_blocks` VALUES ('21', '19', null, '63', '328', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 15:37:12');
INSERT INTO `enumeration_blocks` VALUES ('22', '20', null, '72', '365', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 16:14:13');
INSERT INTO `enumeration_blocks` VALUES ('23', '21', null, null, null, '1', null, '1', '1', '2', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', null, null, null, null, '2012-02-24 16:14:14');
INSERT INTO `enumeration_blocks` VALUES ('24', '22', null, null, null, '1', null, '1', '1', '2', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', null, null, null, null, '2012-02-24 16:14:14');
INSERT INTO `enumeration_blocks` VALUES ('25', '23', null, null, null, '1', null, '1', '1', '2', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', null, null, null, null, '2012-02-24 16:14:15');
INSERT INTO `enumeration_blocks` VALUES ('26', '24', '1', '97', '591', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 16:14:16');
INSERT INTO `enumeration_blocks` VALUES ('27', '24', '2', '42', '234', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 16:14:17');
INSERT INTO `enumeration_blocks` VALUES ('28', '25', null, '91', '489', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 16:14:19');
INSERT INTO `enumeration_blocks` VALUES ('29', '26', null, '75', '403', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 16:14:19');
INSERT INTO `enumeration_blocks` VALUES ('30', '27', null, '73', '514', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 16:14:20');
INSERT INTO `enumeration_blocks` VALUES ('31', '28', null, '118', '690', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('32', '29', null, '121', '785', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('33', '30', null, null, null, '1', null, '1', '1', '2', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:15:03');
INSERT INTO `enumeration_blocks` VALUES ('34', '31', null, '104', '708', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('35', '32', null, '92', '570', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('36', '33', null, '118', '742', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('37', '34', null, '100', '450', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('38', '35', null, '117', '626', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('39', '36', null, null, null, '1', null, '1', '1', '2', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:15:46');
INSERT INTO `enumeration_blocks` VALUES ('40', '37', null, '155', '743', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('41', '38', null, '92', '628', '1', null, '1', '1', '2', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('42', '39', null, '94', '586', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('43', '40', null, '64', '429', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('44', '41', null, '88', '596', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('45', '42', null, '43', '321', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('46', '43', null, '67', '418', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('47', '44', null, '73', '426', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('48', '45', null, '67', '478', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('49', '46', null, '53', '346', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('50', '47', '1', '149', '849', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('51', '47', '2', '78', '408', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('52', '48', null, '45', '306', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('53', '49', null, null, null, '1', null, '1', '1', '3', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:16:53');
INSERT INTO `enumeration_blocks` VALUES ('54', '50', null, '24', '138', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('55', '51', null, '110', '709', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('56', '52', null, '83', '498', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('57', '53', null, '33', '146', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('58', '54', null, '69', '428', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('59', '55', null, '55', '281', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('60', '56', null, '100', '585', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('61', '57', null, '53', '350', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('62', '58', null, '96', '596', '1', null, '1', '1', '3', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('63', '59', null, '22', '115', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('64', '60', null, '115', '731', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('65', '61', null, '161', '694', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('66', '62', null, '70', '407', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('67', '63', null, '118', '734', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('68', '64', null, null, null, '1', null, '1', '1', '4', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:15:31');
INSERT INTO `enumeration_blocks` VALUES ('69', '65', null, '137', '723', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('70', '66', '1', '145', '847', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('71', '66', '2', '10', '40', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('72', '67', null, '97', '456', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('73', '68', null, '291', '691', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('74', '69', null, '583', '583', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('75', '70', null, '540', '540', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('76', '71', null, '287', '287', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-18 12:20:47');
INSERT INTO `enumeration_blocks` VALUES ('77', '72', null, null, null, '1', null, '1', '1', '4', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:17:27');
INSERT INTO `enumeration_blocks` VALUES ('78', '73', null, '85', '454', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('79', '74', null, '122', '678', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('80', '75', null, '76', '501', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('81', '76', null, '152', '775', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('82', '77', null, '76', '594', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('83', '78', null, '94', '480', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('84', '79', null, null, null, '1', null, '1', '1', '4', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:17:10');
INSERT INTO `enumeration_blocks` VALUES ('85', '80', null, null, null, '1', null, '1', '1', '4', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:17:43');
INSERT INTO `enumeration_blocks` VALUES ('86', '81', null, '147', '719', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('87', '82', null, '62', '320', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 15:42:11');
INSERT INTO `enumeration_blocks` VALUES ('88', '83', '1', '133', '642', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, '2012-02-24 15:42:17');
INSERT INTO `enumeration_blocks` VALUES ('89', '83', '2', '41', '244', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('90', '84', null, '56', '318', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('91', '85', '1', '78', '564', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('92', '85', '2', '39', '263', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('93', '86', '1', '70', '410', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('94', '86', '2', '69', '452', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('95', '87', '1', '133', '749', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('96', '87', '2', '13', '90', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('97', '88', null, '109', '653', '1', null, '1', '1', '4', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('98', '89', '1', '140', '784', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('99', '89', '2', '23', '126', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('100', '90', null, '89', '630', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('101', '91', '1', '140', '847', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('102', '91', '2', '42', '224', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('103', '92', null, '67', '345', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('104', '93', null, '101', '655', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('105', '94', null, '79', '436', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('106', '95', null, '84', '467', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('107', '96', null, '80', '469', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('108', '97', null, '151', '611', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('109', '98', null, '160', '785', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('110', '99', null, '127', '715', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('111', '100', '1', '100', '682', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('112', '100', '2', '40', '277', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('113', '101', null, '85', '532', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('114', '102', null, '83', '452', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('115', '103', null, '65', '350', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('116', '104', null, '46', '280', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('117', '105', '1', '130', '831', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('118', '105', '2', '26', '174', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('119', '106', null, '82', '471', '1', null, '1', '1', '5', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('120', '107', null, '56', '266', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('121', '108', '1', '120', '866', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('122', '108', '2', '65', '458', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('123', '109', null, '37', '286', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('124', '110', '1', '80', '577', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('125', '110', '2', '49', '343', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('126', '111', null, '44', '396', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('127', '112', null, '91', '679', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('128', '113', null, '32', '199', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('129', '114', '1', '90', '560', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('130', '114', '2', '56', '354', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('131', '115', null, '61', '419', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('132', '116', '1', '105', '673', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('133', '116', '2', '41', '261', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('134', '117', '1', '80', '597', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('135', '117', '2', '80', '497', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('136', '118', '1', '113', '641', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('137', '118', '2', '113', '670', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('138', '119', '1', '120', '696', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('139', '119', '2', '65', '385', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('140', '120', null, '67', '299', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('141', '121', null, '96', '639', '1', null, '1', '1', '6', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('142', '122', null, '117', '750', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('143', '123', '1', '118', '769', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('144', '123', '2', '44', '282', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('145', '124', null, '69', '426', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('146', '125', null, '145', '748', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('147', '126', '1', '101', '745', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('148', '126', '2', '35', '202', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('149', '127', null, '82', '564', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('150', '128', null, '149', '900', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('151', '129', null, null, null, '1', null, '1', '1', '7', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:18:03');
INSERT INTO `enumeration_blocks` VALUES ('152', '130', null, '105', '745', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('153', '131', '1', '101', '680', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('154', '131', '2', '39', '238', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('155', '132', null, '59', '437', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('156', '133', null, '97', '715', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('157', '134', null, '91', '540', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('158', '135', null, '42', '310', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('159', '136', '1', '103', '735', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('160', '136', '2', '29', '207', '1', null, '1', '1', '7', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('161', '137', '1', '110', '692', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('162', '137', '2', '26', '149', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('163', '138', null, '77', '598', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('164', '139', '1', '100', '622', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('165', '139', '2', '57', '331', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('166', '140', null, '40', '290', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('167', '141', null, '129', '816', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('168', '142', null, '94', '605', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('169', '143', null, '115', '645', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('170', '144', null, '67', '518', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('171', '145', null, '123', '760', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('172', '146', '1', '73', '521', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('173', '146', '2', '73', '473', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('174', '147', '1', '100', '594', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('175', '147', '2', '59', '384', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('176', '148', null, '121', '765', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('177', '149', null, '38', '245', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('178', '150', null, '99', '790', '1', null, '1', '1', '8', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('179', '151', null, '118', '603', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('180', '152', null, '48', '321', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('181', '153', null, '64', '399', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('182', '154', null, '48', '286', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('183', '155', null, '75', '578', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('184', '156', null, '77', '470', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('185', '157', null, '22', '114', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('186', '158', null, '76', '553', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('187', '159', null, '105', '627', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('188', '160', null, '47', '246', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('189', '161', null, '102', '550', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('190', '162', null, '95', '764', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('191', '163', null, '123', '706', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('192', '164', null, '114', '673', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('193', '165', null, '30', '160', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('194', '166', null, '79', '501', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('195', '167', null, '97', '680', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('196', '168', '1', '110', '667', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('197', '168', '2', '23', '145', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('198', '169', null, '87', '527', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('199', '170', null, '84', '447', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('200', '171', null, '90', '492', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('201', '172', null, '125', '720', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('202', '173', null, '124', '771', '1', null, '1', '1', '9', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('203', '174', null, '72', '434', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('204', '175', null, '99', '657', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('205', '176', null, '75', '341', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('206', '177', '1', '120', '733', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('207', '177', '2', '29', '160', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('208', '178', null, '77', '455', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('209', '179', null, '142', '755', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('210', '180', '1', '100', '630', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('211', '180', '2', '94', '544', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('212', '181', null, '144', '694', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('213', '182', null, '105', '724', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('214', '183', null, '44', '236', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('215', '184', null, '134', '756', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('216', '185', null, null, null, '1', null, '1', '1', '10', '1', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', 'No Data', '1', '', null, null, null, '2012-02-16 16:18:19');
INSERT INTO `enumeration_blocks` VALUES ('217', '186', null, '85', '530', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('218', '187', null, '129', '688', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('219', '188', '1', '100', '741', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('220', '188', '2', '17', '122', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('221', '189', null, '60', '411', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('222', '190', null, '96', '552', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('223', '191', null, '106', '684', '1', null, '1', '1', '10', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('224', '192', null, '134', '727', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('225', '193', null, '95', '599', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('226', '194', null, '75', '490', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('227', '195', null, '60', '456', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('228', '196', null, '74', '375', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('229', '197', '1', '136', '635', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('230', '197', '2', '56', '248', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('231', '198', null, '31', '232', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('232', '199', null, '94', '538', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('233', '200', null, '130', '748', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('234', '201', null, '83', '560', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('235', '202', null, '71', '334', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('236', '203', '1', '82', '551', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('237', '203', '2', '33', '221', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('238', '204', null, '74', '505', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('239', '205', '1', '142', '756', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('240', '205', '2', '40', '276', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('241', '206', null, '90', '533', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('242', '207', null, '57', '377', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('243', '208', null, '84', '534', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('244', '209', null, '58', '364', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('245', '210', null, '54', '462', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('246', '211', null, '36', '232', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('247', '212', null, '72', '459', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('248', '213', null, '50', '317', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('249', '214', '1', '133', '767', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('250', '214', '2', '68', '432', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('251', '215', null, '34', '240', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('252', '216', null, '79', '578', '1', null, '1', '1', '11', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('253', '217', null, '118', '637', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('254', '218', null, '89', '589', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('255', '219', null, '100', '584', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('256', '220', null, '133', '677', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('257', '221', null, '15', '84', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('258', '222', '1', '92', '601', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('259', '222', '2', '62', '456', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('260', '223', null, '30', '189', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('261', '224', null, '94', '669', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('262', '225', null, '105', '708', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('263', '226', null, '119', '760', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('264', '227', null, '32', '212', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('265', '228', null, '78', '514', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('266', '229', null, '130', '756', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('267', '230', null, '69', '393', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('268', '231', null, '62', '468', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('269', '232', null, '86', '632', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('270', '233', null, '114', '532', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('271', '234', null, '58', '452', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('272', '235', null, '115', '763', '1', null, '1', '1', '12', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('273', '236', null, '76', '555', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('274', '237', '1', '126', '760', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('275', '237', '2', '42', '207', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('276', '238', null, '103', '769', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('277', '239', '1', '71', '696', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('278', '239', '2', '26', '184', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('279', '240', '1', '72', '661', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('280', '240', '2', '29', '234', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('281', '241', null, '106', '654', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('282', '242', null, '122', '683', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('283', '243', '1', '100', '778', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('284', '243', '2', '19', '88', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('285', '244', null, '74', '541', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('286', '245', null, '74', '475', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('287', '246', null, '86', '694', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('288', '247', null, '65', '502', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('289', '248', '1', '71', '464', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('290', '248', '2', '50', '396', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('291', '249', null, '27', '166', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('292', '250', '1', '100', '560', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('293', '250', '2', '50', '285', '1', null, '1', '1', '13', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('294', '251', null, '47', '275', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('295', '252', '1', '99', '705', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('296', '252', '2', '29', '197', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('297', '253', null, '82', '562', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('298', '254', null, '92', '575', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('299', '255', null, '100', '718', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('300', '256', null, '110', '665', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('301', '257', null, '81', '518', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('302', '258', null, '124', '815', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('303', '259', '1', '114', '679', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('304', '259', '2', '18', '101', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('305', '260', null, '103', '529', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('306', '261', null, '111', '687', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('307', '262', null, '59', '328', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('308', '263', null, '76', '413', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('309', '264', '1', '103', '733', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('310', '264', '2', '23', '170', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('311', '265', null, '87', '536', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('312', '266', null, '114', '833', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
INSERT INTO `enumeration_blocks` VALUES ('313', '267', null, '56', '384', '1', null, '1', '1', '14', '1', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', 'Completed', '1', null, null, null, null, null);
